### ISSUE TITLE
Blueharvest should implement a centralized admin console

### ISSUE THREAD

**Issue by ybotspawn** [DIOS-Tech/BlueHarvest#14]
Admin console should support multiple levels of administrators with multiple types of privileged access

Additional sub requirements:

- [ ] BlueHarvest should have an employee manager https://github.com/DIOS-Tech/BlueHarvest/issues/8

**Comment by frankhale** [comment]
Related issue https://github.com/DIOS-Tech/BlueHarvest/issues/8

**Comment by frankhale** [comment]
This is going to be added to a task list in https://github.com/DIOS-Tech/BlueHarvest/issues/1
