### ISSUE TITLE
BlueHarvest should support daily notifications

### ISSUE THREAD

**Issue by ybotspawn** [DIOS-Tech/BlueHarvest#16]
Email
SMS
Web

**Comment by frankhale** [comment]
SMS as in send a phone message?

**Comment by frankhale** [comment]
I smell a Windows service project here.

**Comment by swapneeld** [comment]
For Web notification can use - [toastr] (https://github.com/CodeSeven/toastr)

**Comment by frankhale** [comment]
This is going to be added to a task list in https://github.com/DIOS-Tech/BlueHarvest/issues/1
