### ISSUE TITLE
Blueharvest should implement a web API

### ISSUE THREAD

**Issue by ybotspawn** [DIOS-Tech/BlueHarvest#17]
API should allow both inputs and outputs to be serialized

**Comment by frankhale** [comment]
I definitely agree here. I think the Web API should be a separate project from the Web app because it is a completely separate entity in and of itself.

The web app is just a consumer of the Web API which means all that database stuff has to be done in Web API not in the Web app.

**Comment by frankhale** [comment]
All the heavy lifting ought to be done in the Web API not the Web app.

When the Web API is separated from the Web app then the Web app becomes fairly easy and straight forward to implement. Lots of client side magic can be done to consume the API's.This could be implemented as a single page application.

**Comment by frankhale** [comment]
With a Web API one can envision other types of apps that can consume it.

**Comment by frankhale** [comment]
NOTE: This will be closed once we reach milestone v0.2.0. That milestone outlines the minimal behavior necessary. Not going to hold these issues up for weeks / months. Gonna move things right along as swiftly as possible.

**Comment by frankhale** [comment]
This is going to be added to a task list in https://github.com/DIOS-Tech/BlueHarvest/issues/1
