### ISSUE TITLE
add change log in sql

### ISSUE THREAD

**Issue by ybotspawn** [DIOS-Tech/BlueHarvest#23]

**Comment by ybotspawn** [comment]
Access Log model prototype written, issue pending sql script update

**Comment by frankhale** [comment]
We should discuss the models. What is your thought on their usage? Where will they be used? I mean we will be using the SQL Type Provider which will provide all the types coming from the DB without any coding from us. That is the magic of Type Providers. Will these models be used for view models in the web app?

**Comment by frankhale** [comment]
Reference: https://github.com/DIOS-Tech/BlueHarvest/issues/29

**Comment by frankhale** [comment]
Closing in favor of https://github.com/DIOS-Tech/BlueHarvest/issues/29
