### ISSUE TITLE
UI discussion

### ISSUE THREAD

**Issue by frankhale** [DIOS-Tech/BlueHarvest#28]
This issue is here to track how the UI will be designed. I'd imagine page mockups and/or specific UI screenshots would be pasted here (but maybe that's overkill).

**Comment by ybotspawn** [comment]
I agree with you mockups etc.

**Comment by frankhale** [comment]
So I'm mocking up various sections of the app and this is what I have so far:

Administration, Daily Schedule, Vacation Requests, Employee Data and Employee Tasks

What others need to be in that list?

**Comment by frankhale** [comment]
After a user logs in I'm thinking a dashboard can be shown. I call it the quick launch. Here is a mockup:

![quick-launch](https://cloud.githubusercontent.com/assets/190154/6141093/d424fc86-b16e-11e4-8b60-f15a508423ed.PNG)

**Comment by ybotspawn** [comment]
Ummmm think that's it....

**Comment by frankhale** [comment]
FYI, yummy bootstrap themes here: http://bootswatch.com/

**Comment by frankhale** [comment]
This issue is unfortunate, we should have issues opened for specific things rather than open ended discussion. I'm gonna close this. If there is a specific UI issue let's open it and discuss it.
