### ISSUE TITLE
Screenshots of old system

### ISSUE THREAD

**Issue by frankhale** [DIOS-Tech/BlueHarvest#32]
@ybotspawn, can you take screenshots of old system and email them to me? I'd like to see how the views were set up to give me an indication of what was already present.

**Comment by ybotspawn** [comment]
Sure I'll get the leave request screen shots tomorrow

**Comment by frankhale** [comment]
Was the "leave request system" the only one or was there another one? I cannot remember.

**Comment by frankhale** [comment]
But cool, any screenshots you can produce would be great! Thanks.

**Comment by frankhale** [comment]
Did you get the screenshots today?

**Comment by ybotspawn** [comment]
I'll have them tomorrow, got tied up today

**Comment by frankhale** [comment]
I'm gonna hold your feet to the fire! LOL!

**Comment by frankhale** [comment]
You don't need to post them here, just email me the screenshots and then close this issue.

**Comment by frankhale** [comment]
Bueller?

**Comment by ybotspawn** [comment]
![request-1](https://cloud.githubusercontent.com/assets/280946/6160573/c4c00190-b232-11e4-977e-0f894d506f71.png)
![request-2](https://cloud.githubusercontent.com/assets/280946/6160574/c8422e74-b232-11e4-8548-ff1b3f78ec58.png)
![schedule-1](https://cloud.githubusercontent.com/assets/280946/6160577/cab3a0f2-b232-11e4-98ed-e75156722e9d.png)
![schedule-2](https://cloud.githubusercontent.com/assets/280946/6160578/ccb63d6a-b232-11e4-99b8-72881df3bce3.png)

**Comment by frankhale** [comment]
Cool, thanks!

**Comment by frankhale** [comment]
These are extremely helpful, thank you!
