### ISSUE TITLE
Database solidification and freeze run down

### ISSUE THREAD

**Issue by frankhale** [DIOS-Tech/BlueHarvest#66]
This task marks the solidification and freezing of the initial db. We should have all of the core tables in, all of the columns we want to capture the data we need and the relationships should be squared away. This will be necessary so that we can freeze the DB and then move on to the F# data access layer.

**Comment by frankhale** [comment]
I am currently working on a few changes but I think the initial database is mostly done. Once I finish some stuff tonight I'm going to throw it in your court @ybotspawn so that we can get this thing frozen.

**Comment by frankhale** [comment]
This has been added to the Initial DB Freeze milestone and set to a tentative date 28 February, obviously the sooner the better. What changes to the current schema do you think need to be made? If none then we'll freeze it now and move on to finishing up the initial data access layer.

**Comment by frankhale** [comment]
Okay it's been 5 days and no comment so I'm going to assume no more changes to the database right now.

**Comment by ybotspawn** [comment]
Yes, sorry for now no more DB changes.... I should be able to resume some
effort on this this weekend. Multiple emergencies at work

**Comment by frankhale** [comment]
Okay. This means that now the F# database layer can be created against the current DB as is. Any database changes will be made later after the data access layer is wrote.
