### ISSUE TITLE
BlueHarvest should have an employee manager 

### ISSUE THREAD

**Issue by ybotspawn** [DIOS-Tech/BlueHarvest#8]
This manager should be able to handle an unlimited number of levels of hierarchy

**Comment by frankhale** [comment]
What exactly entails a employee manager. What things must the employee manager do besides manage employees, LOL! Given the current set of DB tables what tables would be involved in managing this data?

**Comment by frankhale** [comment]
Moving this to https://github.com/DIOS-Tech/BlueHarvest/issues/14
