### ISSUE TITLE
Make README more useful

### ISSUE THREAD

**Issue by frankhale** [DIOS-Tech/BlueHarvest#80]
The current README is not good enough in the following area, specifically in the need to install io.js, bower and then use bower to grab web dependencies for the Web.App and Web.Api projects. 

In short, the README needs to convey that certain types of requirements have been moved away from Nuget and replaced by Bower for dependencies such as jQuery, Bootstrap, Lodash, etc.. any dependencies that are JavaScript specific or client residing.

**Comment by frankhale** [comment]
Be gone issue, be gone I say!

**Comment by ybotspawn** [comment]
Lol I sware ill close a couple this week!

**Comment by frankhale** [comment]
No worries!

**Comment by frankhale** [comment]
What other shit needs done? We need to create some more issues that are doable in short order so shit can get done. Yeah we have that big REQUIREMENTS issue but it's so big it's like WTF. We need some more streamlined targeted issues. Ideas? Some shit that is doable in a couple hours at most.
